SELECT * FROM Tavern;
SELECT * FROM Guests;

SELECT *
FROM INFORMATION_SCHEMA.TABLES WHERE table_Name = 'Tavern';
select * from sys.all_columns;

/*
select CONCAT(Tavern, ' ', TABLE_TYPE), *
FROM INFORMATION_SCHEMA.TABLES WHERE table_Name = 'Tavern';
*/
SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE;

SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS;
